import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import SelectDog from "../components/SelectDog/SelectDog";
import Head from "next/head";

export default function SelectPage() {
    return (
        <>
            <Head>
                <title>Pocket Pals</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <div>
                <SelectDog />
            </div>
        </>
    )
}